# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WEats' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WEats

  pod 'IQKeyboardManagerSwift'
  pod ‘Firebase/Core’
  pod ‘Firebase/Auth’
  pod ‘Firebase/Database’
  pod ‘Firebase/Storage’
  pod ‘Firebase/Messaging’
  pod 'DropDown'
  pod 'Kingfisher'
  pod ‘SwiftKeychainWrapper’
  pod ‘CircleSlider’
  pod 'SDWebImage'
  pod 'TransitionButton', '~> 0.2’
  pod 'DropDown'
  pod 'ShadowView'

  target 'WEatsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WEatsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
